Repository hashicorp/terraform-provider-time, pull requests merged in 2023-08, with the labels that each got.

#225 Adding Terraform 1.5.* to test matrix
  .github/workflows/test.yml
Labels: enhancement, size/XS

#230 Use terraform-plugin-framework-timetypes for RFC3339 string attributes
  go.mod
  go.sum
  internal/provider/resource_time_offset.go
  internal/provider/resource_time_rotating.go
  internal/provider/resource_time_rotating_test.go
  internal/provider/resource_time_sleep.go
  internal/provider/resource_time_static.go
  internal/provider/resource_time_static_test.go
  internal/validators/timevalidator/is_rfc3339_time.go
  internal/validators/timevalidator/is_rfc3339_time_test.go
Labels: dependencies, technical-debt, size/XL

#232 cdktf: update documentation
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/offset.md
  docs/cdktf/python/resources/rotating.md
  docs/cdktf/python/resources/sleep.md
  docs/cdktf/python/resources/static.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/offset.md
  docs/cdktf/typescript/resources/rotating.md
  docs/cdktf/typescript/resources/sleep.md
  docs/cdktf/typescript/resources/static.md
Labels: size/M

#234 cdktf: update documentation
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/offset.md
  docs/cdktf/python/resources/rotating.md
  docs/cdktf/python/resources/sleep.md
  docs/cdktf/python/resources/static.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/offset.md
  docs/cdktf/typescript/resources/rotating.md
  docs/cdktf/typescript/resources/sleep.md
  docs/cdktf/typescript/resources/static.md
Labels: size/M
