Repository hashicorp/terraform-provider-time, pull requests merged in 2023-11, with the labels that each got.

#258 cdktf: update documentation
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/offset.md
  docs/cdktf/python/resources/rotating.md
  docs/cdktf/python/resources/sleep.md
  docs/cdktf/python/resources/static.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/offset.md
  docs/cdktf/typescript/resources/rotating.md
  docs/cdktf/typescript/resources/sleep.md
  docs/cdktf/typescript/resources/static.md
Labels: size/S

#262 .github: Add CI for changie
  .github/workflows/ci-changie.yml
Labels: size/XS

#263 Add changelogs for `v0.9.2` release
  .changes/unreleased/NOTES-20230303-162903.yaml
  .changes/unreleased/NOTES-20231127-093945.yaml
Labels: size/XS

#265 .github: Update workflows to use actions variables
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: size/S

#266 Automatically close associated milestone on release
  .goreleaser.yml
Labels: size/XS

#189 Add support for multiple offsets to time_offset module
  .changes/unreleased/BUG FIXES-20231130-135645.yaml
  docs/resources/offset.md
  examples/resources/time_offset/resource_multiple_offset.tf
  internal/provider/resource_time_offset.go
  internal/provider/resource_time_offset_test.go
  templates/resources/offset.md.tmpl
Labels: tf-devex-triage, size/M
