Repository hashicorp/terraform-provider-time, pull requests merged in 2024-03, with the labels that each got.

#280 `function/rfc3339_parse`: Add RFC3339 parsing function
  .changes/unreleased/FEATURES-20240116-135142.yaml
  .github/workflows/test.yml
  docs/functions/rfc3339_parse.md
  examples/functions/rfc3339_parse/function.tf
  go.mod
  internal/provider/function_rfc3339_parse.go
  internal/provider/function_rfc3339_parse_test.go
  internal/provider/provider.go
  templates/functions/rfc3339_parse.md.tmpl
Labels: enhancement, dependencies, size/XL

#299 docs: Fix YAML frontmatter in template
  .changes/unreleased/NOTES-20240311-150600.yaml
  docs/functions/rfc3339_parse.md
  templates/functions/rfc3339_parse.md.tmpl
Labels: documentation, size/XS

#302 cdktf: update documentation
  docs/cdktf/python/functions/rfc3339_parse.md
  docs/cdktf/typescript/functions/rfc3339_parse.md
Labels: size/M
