Repository hashicorp/terraform-provider-time, pull requests merged in 2024-01, with the labels that each got.

#277 cdktf: update documentation
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/offset.md
  docs/cdktf/python/resources/rotating.md
  docs/cdktf/python/resources/sleep.md
  docs/cdktf/python/resources/static.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/offset.md
  docs/cdktf/typescript/resources/rotating.md
  docs/cdktf/typescript/resources/sleep.md
  docs/cdktf/typescript/resources/static.md
Labels: size/S

#278 Add `issues: write` permission to release workflow to close associated GitHub milestone
  .github/workflows/release.yml
Labels: size/XS

#282 cdktf: update documentation
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/offset.md
  docs/cdktf/python/resources/rotating.md
  docs/cdktf/python/resources/sleep.md
  docs/cdktf/python/resources/static.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/offset.md
  docs/cdktf/typescript/resources/rotating.md
  docs/cdktf/typescript/resources/sleep.md
  docs/cdktf/typescript/resources/static.md
Labels: size/XS

#285 .github/workflows: Update to hashicorp/ghaction-terraform-provider-release@v3
  .github/workflows/release.yml
Labels: size/XS

#289 Added GHA dependabot config for managing hashicorp actions
  .github/dependabot.yml
Labels: dependencies, size/XS
