Repository hashicorp/terraform-provider-time, pull requests merged in 2025-02, with the labels that each got.

#388 chore: Fix for golangci-linters
  .golangci.yml
  internal/timetesting/int64_between_knownvalue_test.go
Labels: size/XS

#350 `function/parse_duration`: Add duration parsing function
  .changes/unreleased/FEATURES-20250123-191529.yaml
  docs/functions/duration_parse.md
  examples/functions/duration_parse/function.tf
  internal/provider/function_duration_parse.go
  internal/provider/function_duration_parse_test.go
  internal/provider/provider.go
  templates/functions/duration_parse.md.tmpl
Labels: size/XL

#389 cdktf: update documentation
  docs/cdktf/python/functions/duration_parse.md
  docs/cdktf/typescript/functions/duration_parse.md
Labels: size/M

#385 New Provider Function: `unix_timestamp_parse`
  .changes/unreleased/FEATURES-20250205-155509.yaml
  docs/functions/unix_timestamp_parse.md
  examples/functions/unix_timestamp_parse/function.tf
  internal/provider/function_unix_timestamp_parse.go
  internal/provider/function_unix_timestamp_parse_test.go
  internal/provider/provider.go
  internal/provider/provider_test.go
Labels: size/L
